### PR TITLE
Ignore error from strict method signature rule

### PR DESCRIPTION
**Pull request by iluuu1994**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'm too eager at merging today :D

**Comment by iluuu1994** [comment]
@ondrejmirtes Good for me 😆 I'll create another pull request for phpstan to remove the parameter and ignore any remaining errors.

**Comment by iluuu1994** [comment]
So, apparently there's one more bug when resolving phpDocs from a method in a nested trait. I'll take a look at that tomorrow.

**Comment by ondrejmirtes** [comment]
BTW: 90% real-world problems at my job's codebase the rule found (with reportMaybes false) is about overriding parent return type `void` with something specific. I think we could relax this a bit, because I think it doesn't break LSP - when the parent interface is typehinted, the user code doesn't read the result, so it isn't bothered when a child implementation returns something there...

**Comment by iluuu1994** [comment]
@ondrejmirtes True. I can adjust that tomorrow.

**Comment by ondrejmirtes** [comment]
One more thing I'm realizing - the rule should probably be switched off for static methods. Yes, it can be invoked like `$foo::doSomething()` and LSP applies there, but that's pretty uncommon.

**Comment by ondrejmirtes** [comment]
I did the proposed changes on phpstan/phpstan master, please check them out :)

**Pull request merged**
