### PR TITLE
Added MissingArrayValueTypeInMethodParameterRule

### PR DESCRIPTION
**Pull request by CZechBoY**
Hi,
I just want to make first step to array and iterable type checking.

### CODE REVIEW

**Comment by CZechBoY** [comment]
@ondrejmirtes Anything I can improve here?

**Comment by ondrejmirtes** [comment]
As I suggested in the other PR, this could be done in the existing rules for the sake of consistency. Feel free to join forces with @thewilkybarkid, thanks.

**Comment by CZechBoY** [comment]
Something like this?
https://github.com/CZechBoY/phpstan-strict-rules/commit/d39bdd285aba855f4035723589123b139cdeb7bf

**Comment by ondrejmirtes** [comment]
Yeah, similar to this, but it could work for all iterables, not just arrays.

**Pull request closed without merging**
