### PR TITLE
Added: disallow usage of backtick operator

### PR DESCRIPTION
**Pull request by kralmichal**
This PR disallows usage of backtick operator. 

This is followup on https://github.com/phpstan/phpstan-strict-rules/issues/89

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Awesome, this is perfect! Thank you very much.

**Comment by kralmichal** [comment]
Perfect, I'm glad I got it right. Happy to contribute.

**Comment by ondrejmirtes** [comment]
The build failure is unrelated, I'm gonna fix it on master :)

**Comment by kralmichal** [comment]
Ok great, thanks

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
