### PR TITLE
Fixed incorrect branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, what consequences does this have? This is generally needed when you want to have `^1.1` in your composer.json but the thing you want is not yet released. Since I release any merged PRs in extensions immediately, I don't think I need to update these aliases.

**Comment by GrahamCampbell** [comment]
The problem is that if someone asks for `1.0.*` but have their minimum stability set to dev, composer can fetch the code that is actually 1.1.1-dev because the branch alias is wrong.

**Comment by ondrejmirtes** [comment]
Alright, thanks.

**Comment by GrahamCampbell** [comment]
My preferred solution here is not use branch alias, and instead name the branches such that packagist can understand them. `1.0`, `1.1`, `1.2`. No master branch.

**Pull request merged**
