### PR TITLE
Enable maybes in MethodSignatureRule

### PR DESCRIPTION
**Pull request by iluuu1994**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Thanks :)

**Comment by iluuu1994** [comment]
Hehe that was too soon, the ignores for the `Rule::processNode` `$node` parameter are missing. I'll create a pull request in a second.

**Comment by Majkl578** [comment]
A test would be nice to see what changed.

**Comment by iluuu1994** [comment]
@Majkl578 The tests are over here: https://github.com/phpstan/phpstan/pull/1292

**Pull request merged**
