### PR TITLE
Rules for strict identity comparison

### PR DESCRIPTION
**Pull request by lookyman**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
I'm not sure about this one because `==` and `!=` is sometimes justifiable for comparing `DateTime`/`DateTimeImmutable` instances and maybe something else too. What do you think?

**Comment by lookyman** [comment]
Justifiable? Sure. I still think that they should be removed from the language anyway.. :)

Maybe I could check that there are `DateTimeInterface` instances on both sides and do not report an error? Or even have like a parameter that controls this?

**Comment by ondrejmirtes** [comment]
Or maybe it's fine because since PHP 7.1 DateTimes contain microseconds and that comparison won't yield desired results anyway? 😊

cc @Ocramius what do you think, are `==` and `!=` justifiable in strictly typed code?

**Comment by Ocramius** [comment]
If the types are known, `===` and `!==` should ALWAYS be used.

`==` is also valid when comparing value objects between each other. `new EmailAddress('me@example.com') == $otherMailAddress` is valid, correct and simple.

If `mixed` or union scalars are used, `==` and `!=` are actually correct in many scenarios.

**Comment by ondrejmirtes** [comment]
I dislike comparing objects using `==` because that leaks the internal state of the object, so two objects with equal values would have `false` in case some of their internal properties would be different, like cache or something...

So what's the conclusion? Do you think that this rule is not worthwhile to be included, or that it should be checked only in some specific cases?

**Comment by lookyman** [comment]
Hmm, maybe we could approach this from a slightly different angle and report errors just when there are provably different types on either side?

**Comment by Ocramius** [comment]
@ondrejmirtes value objects are compared by value, and correctly so for most "friend object" implementations.

Only in very rare cases two value objects are equivalent even if internal state is different, and in that case the equivalence is probably a domain logic issue (it's not equivalence).

**Comment by ondrejmirtes** [comment]
@lookyman That might be good idea and maybe even for `phpstan/phpstan` (obvious bug, not just an opinionated rule). Reporting that on both sides of `==` and `!=` is an object of different type.

@Ocramius ok :)

**Comment by VasekPurchart** [comment]
> Reporting that on both sides of == and != is an object of different type.

I think reporting this makes sense for `phpstan/phpstan` and also being more strict in `phpstan-strict-rules` rules makes sense for me, so I am for reporting any `==` (with the exception of mixed types and native comparable types).

There are two problems with comparing value objects by `==`:

1) Comparing compares their internal state hence violating encapsulation as @ondrejmirtes already mentioned. This holds true even for immutable value object since the public surface is what counts actually. The problem is of course not only theoretical, since there can be some lazy-initialized values in the object.

2) Telling what objects are intended as value objects is kind of difficult and since this can lead to errors more often than not, then I think the default state should be reporting errors on all objects withm maybe a configurable list of types (either directly value object classes or some interfaces which they usually implement in your code base, like custom `Comparable` iface).

**Comment by lookyman** [comment]
Ok, I will hop over to `phpstan/phpstan` and prepare something along the lines of "comparing ThisObject and ThatObject with == always evaluates to false", and come back to this later.

**Comment by realjjaveweb** [comment]
@ondrejmirtes This may have been a bug and last time I checked php-src, it does compare microseconds and is a documented behavior at least in https://www.php.net/manual/en/datetime.diff.php
> Note:
[DateTimeImmutable](https://www.php.net/manual/en/class.datetimeimmutable.php) and [DateTime](https://www.php.net/manual/en/class.datetime.php) objects can be compared using [comparison operators](https://www.php.net/manual/en/language.operators.comparison.php).

DateTime and DateTimeImmutable have special comparison handlers in php-src. So there should be option to make an exception for these 2 at least.

For other objects - refer to https://www.php.net/manual/en/language.oop5.object-comparison.php :
> When using the comparison operator (==), object variables are compared in a simple manner, namely: Two object instances are equal if they have the same attributes and values (**values are compared with ==**), **and are instances of the same class.**

So for regular objects I do see an issue here if 1 object would have `false` and other one `null` on a `?bool`. I understand why they did this - it's because the same way it can compare nested objects - but I don't know... I keen to have for classes custom comparators...

**Comment by ondrejmirtes** [comment]
@realjjaveweb You're commenting on a 6 year old closed PR and I have no idea what you're trying to say 😊 Please if you have a bug to report or a feature request, open an issue.

**Pull request closed without merging**
